videobackground.settings:
  type: mapping
  label: Settings
  mapping:
    included_selectors:
      type: string
    mp4:
      type: string
      label: '.mp4 Video'
    ogv:
      type: string
      label: '.ogv Video'
    webm:
      label: '.webm Video'
    poster:
      type: string
      label: 'Video Poster'
    volume:
      type: integer
      label: 'Video volume'
    playbackrate:
      type: integer
      label: 'Video playbackrate'
    muted:
      type: integer
      label: 'Video muted'
    loop:
      type: integer
      label: 'Video loop'
    autoplay:
      type: integer
      label: 'Video autoplay'
    position:
      type: string
      label: 'Video position'
    postertype:
      type: string
      label: 'Video postertype'
    resizing:
      type: integer
      label: 'Video resizing'
    bgcolor:
      type: string
      label: 'Video bgcolor'
    classname:
      type: string
      label: 'Video classname'
